language: csharp
mono: none
dotnet: 2.0.0
dist: trusty

env:
  global:
    - CONFIGURATION=Release

addons:
  sonarcloud:
    organization: "lxconan-github"
    token:
      secure: $SONAR_TOKEN

script:
  - sonar-scanner
  - cd test/Axe.Cli.Parser.Test
  - dotnet restore
  - dotnet test
